# Generated by Django 3.0.5 on 2020-08-15 18:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New Board', max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('date_submit', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed', models.BooleanField(default=False)),
                ('recurring', models.BooleanField(default=False)),
                ('recur_interval', models.DurationField(blank=True)),
                ('recur_adjust', models.BooleanField(default=False)),
                ('due_ool', models.BooleanField(default=False)),
                ('date_due', models.DateTimeField(blank=True)),
                ('urgent', models.BooleanField(default=False)),
                ('today', models.BooleanField(default=False)),
                ('overdue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TodoSubitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('completed', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportsite.TodoItem')),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='New To-Do', max_length=30)),
                ('subtitle', models.CharField(blank=True, default='', max_length=30)),
                ('date_submit', models.DateTimeField(default=django.utils.timezone.now)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportsite.Board')),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportsite.TodoList'),
        ),
    ]
