# Generated by Django 3.0.5 on 2020-12-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='file',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
