# Generated by Django 3.0.5 on 2020-12-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0002_program_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='file',
            new_name='code',
        ),
        migrations.AddField(
            model_name='program',
            name='demo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='html',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
