# Generated by Django 3.0.5 on 2020-12-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0003_auto_20201218_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
