# Generated by Django 3.0.5 on 2020-12-31 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0004_program_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='demo',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='html',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
