# Generated by Django 3.0.5 on 2020-12-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0005_auto_20201230_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.FileField(null=True, upload_to='code'),
        ),
    ]
