# Generated by Django 3.0.5 on 2021-01-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0006_auto_20201230_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='code',
        ),
        migrations.AddField(
            model_name='program',
            name='python',
            field=models.FileField(null=True, upload_to='code/python'),
        ),
    ]
