# Generated by Django 3.0.5 on 2021-01-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0007_auto_20210103_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='js',
            field=models.FileField(blank=True, null=True, upload_to='code/js'),
        ),
        migrations.AddField(
            model_name='program',
            name='r',
            field=models.FileField(blank=True, null=True, upload_to='code/r'),
        ),
        migrations.AlterField(
            model_name='program',
            name='python',
            field=models.FileField(blank=True, null=True, upload_to='code/python'),
        ),
    ]
