# Generated by Django 3.0.5 on 2020-12-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artpiece',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artpiece',
            name='tags',
            field=models.TextField(null=True),
        ),
    ]
