# Generated by Django 3.0.5 on 2020-12-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20201215_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='tags',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='tags',
            field=models.ManyToManyField(to='art.ArtTag'),
        ),
    ]
