# Generated by Django 3.0.5 on 2020-12-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20201218_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artpiece',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
